name = "runr"
compatibility_date = "2024-09-23"

[vars]
SMTP_HOST = "send.smtp.com"
SMTP_PORT = "587"
SMTP_USER = "noreply@micrositeidpl.in"
SMTP_PASS = "634'=DTmWW80"
EMAIL_TO = "sagar@runr.in"
EMAIL_CC_1 = "suhas@runr.in"
EMAIL_CC_2 = "gurmeetsingh@runr.in"
EMAIL_FROM = "RUNR <noreply@micrositeidpl.in>"
