name = "runr"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
SMTP_HOST = "send.smtp.com"
SMTP_PORT = "587"
SMTP_USER = "noreply@micrositeidpl.in"
SMTP_PASS = "634'=DTmWW80$"
EMAIL_TO = "mansi.pinjani@insomniacs.in"
EMAIL_CC_1 = "rutik@insomniacs.in"
EMAIL_CC_2 = "kinal@insomniacs.in"
EMAIL_FROM = "noreply@micrositeidpl.in"
